name: Run tests on push
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Test
        run: mvn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}